import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Topbar";
import Header from "@/components/Header";
import Menu from "@/components/Menu";
import PromotionSection from "@/components/PromotionSection";
import HotSales from "@/components/HotSales";
import ProductCategory from "@/components/PromotionProduct";
import CosmeticsCategory from "@/components/PromotionCosmetics";
import FeatureCategories from "@/components/FeatureCategories";
import PromotionMedicine from "@/components/PromotionMedicine";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Topbar />
        <Header />
        <Menu />
        <PromotionSection />
        <HotSales />
        <ProductCategory />
        <CosmeticsCategory />
        <FeatureCategories />
        <PromotionMedicine />
        {/* Main content */}
        {children}
      </body>
    </html>
  );
}
